# Generated by Django 4.2.30 on 2026-05-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('goatra', models.CharField(max_length=100)),
                ('relationship_title', models.CharField(choices=[('PARDADI', 'PARDADI'), ('PARDADA', 'PARDADA'), ('GRAND_MOTHER_PATERNAL', 'GRAND MOTHER Paternal'), ('GRAND_FATHER_PATERNAL', 'GRAND FATHER Paternal'), ('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('GRAND_DAUGHTER', 'GRAND DAUGHTER'), ('GRAND_SON', 'GRAND SON'), ('MAMA', 'MAMA'), ('MAMI', 'MAMI'), ('MASA', 'MASA'), ('MASI', 'MASI'), ('FAI', 'FAI'), ('FUVA', 'FUVA'), ('BHATRIJO', 'BHATRIJO'), ('BHATRIJI', 'BHATRIJI'), ('BHANO', 'BHANO'), ('BHANI', 'BHANI'), ('SALO', 'SALO'), ('SALI', 'SALI'), ('MOTAPAPA', 'MOTAPAPA'), ('MOTAMOMMY', 'MOTAMOMMY'), ('KAKA', 'KAKA'), ('KAKI', 'KAKI'), ('SASU', 'SASU'), ('SASRA', 'SASRA'), ('HUSBAND', 'HUSBAND'), ('WIFE', 'WIFE'), ('BHABHI', 'BHABHI'), ('NAND', 'NAND'), ('GRAND_MOTHER_MATERNAL', 'GRAND MOTHER Maternal'), ('GRAND_FATHER_MATERNAL', 'GRAND FATHER Maternal')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family_members/')),
                ('contact_number_1', models.CharField(max_length=15)),
                ('contact_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('current_address', models.TextField()),
                ('native', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Business', 'Business'), ('Other', 'Other')], max_length=50)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bank_details', models.TextField()),
                ('upi_details', models.CharField(max_length=100)),
                ('aadhar_card_number', models.CharField(max_length=12, unique=True)),
                ('pan_card_number', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
