# Generated by Django 4.2.30 on 2026-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='division',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
