# Generated by Django 4.2.30 on 2026-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_remove_familymember_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='job_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Other', 'Other')], max_length=50),
        ),
    ]
