# Generated by Django 4.2.30 on 2026-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_familymember_division_alter_familymember_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='aadhar_card_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='pan_card_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship_title',
            field=models.CharField(max_length=100),
        ),
    ]
