# Generated by Django 4.2.30 on 2026-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_alter_familymember_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='upi_details',
        ),
        migrations.AddField(
            model_name='familymember',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='branch_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='upi_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='upi_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
