# Generated by Django 6.0.5 on 2026-05-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_remove_familymember_bank_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
