# Generated by Django 4.2.30 on 2026-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_familymember_favorite_food_familymember_kuldevi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
