# Generated by Django 4.2.30 on 2026-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_remove_familymember_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='c_apartment',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='c_area',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='c_block_no',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='c_city',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='c_landmark',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='c_pincode',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='c_state',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='p_apartment',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='p_area',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='p_block_no',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='p_city',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='p_landmark',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='p_pincode',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='p_state',
        ),
        migrations.AddField(
            model_name='familymember',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
