# Generated by Django 4.2.30 on 2026-05-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_remove_familymember_c_apartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuldevDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(choices=[('Kuldev', 'Kuldev'), ('Kuldevi', 'Kuldevi')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuldev_details', to='myproject.familymember')),
            ],
        ),
    ]
