# Generated by Django 4.2.30 on 2026-05-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_kuldevdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nived_foods', to='myproject.familymember')),
            ],
        ),
    ]
