# Generated by Django 4.2.30 on 2026-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_nivedfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivedfood',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
