# Generated by Django 4.2.30 on 2026-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_nivedfood_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuldevdetail',
            name='dev_type',
            field=models.CharField(max_length=100),
        ),
    ]
