# Generated by Django 4.2.30 on 2026-05-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_alter_kuldevdetail_dev_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='goatra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
