# Generated by Django 4.2.30 on 2026-05-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0016_alter_familymember_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='myproject.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='myproject.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='myproject.familymember'),
        ),
    ]
