# Generated by Django 4.2.30 on 2026-05-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0018_familymember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
    ]
