# Generated by Django 4.2.30 on 2026-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0019_remove_familymember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='address_type',
            field=models.CharField(blank=True, choices=[('City', 'City'), ('Village', 'Village')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='block_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='other_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='society',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
