# Generated by Django 4.2.30 on 2026-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0020_familymember_address_type_familymember_block_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='family_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
