# Generated by Django 4.2.30 on 2026-05-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0021_familymember_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='division',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='property_value',
        ),
    ]
