# Generated by Django 4.2.30 on 2026-05-12 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0023_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
