# Generated by Django 4.2.30 on 2026-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0025_familymember_age_familymember_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
