# Generated by Django 4.2.30 on 2026-05-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0026_familymember_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
