# Generated by Django 4.2.30 on 2026-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0027_familymember_father_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='generation',
            field=models.IntegerField(default=1),
        ),
    ]
