# Generated by Django 4.2.30 on 2026-05-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0028_familymember_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='husband_units', to='myproject.familymember')),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wife_units', to='myproject.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='ChildRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_relations', to='myproject.familymember')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='myproject.familyunit')),
            ],
        ),
    ]
